In [3]:
import os 
path = "D:\\Dana\\traffic crashes\\chicago"
os.chdir(path)

In [5]:
import pandas as pd 
dfv = pd.read_csv('Traffic_Crashes_Vehicles_20240409.csv', low_memory=False)
dfd = pd.read_csv('Traffic_Crashes_People_20240409.csv', low_memory=False)

In [11]:
#1676302
#1676302 rows × 71 columns
len(pd.unique(dfv['CRASH_RECORD_ID']).tolist()) # 821716 unique crash IDs
dfv

,CRASH_UNIT_ID,CRASH_RECORD_ID,CRASH_DATE,UNIT_NO,UNIT_TYPE,NUM_PASSENGERS,VEHICLE_ID,CMRC_VEH_I,MAKE,MODEL,...,TRAILER1_LENGTH,TRAILER2_LENGTH,TOTAL_VEHICLE_LENGTH,AXLE_CNT,VEHICLE_CONFIG,CARGO_BODY_TYPE,LOAD_TYPE,HAZMAT_OUT_OF_SERVICE_I,MCS_OUT_OF_SERVICE_I,HAZMAT_CLASS
0,1717556,7b1763088507f77e0e552c009a6bf89a4d6330c7527706...,12/06/2023 03:24:00 PM,1,DRIVER,NaN,1634931.0,NaN,NISSAN,SENTRA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1717574,2603ff5a88f0b9b54576934c5ed4e4a64e8278e005687b...,12/06/2023 04:00:00 PM,2,DRIVER,NaN,1634978.0,NaN,CHRYSLER,SEBRING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1717579,a52ef70e33d468b855b5be44e8638a564434dcf99c0edf...,12/06/2023 04:30:00 PM,1,DRIVER,NaN,1634948.0,NaN,SUBARU,OUTBACK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1720118,609055f4b1a72a44d6ec40ba9036cefd7c1287a755eb6c...,12/10/2023 12:12:00 PM,1,DRIVER,NaN,1637401.0,NaN,TOYOTA,RAV4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1720119,609055f4b1a72a44d6ec40ba9036cefd7c1287a755eb6c...,12/10/2023 12:12:00 PM,2,DRIVER,NaN,1637408.0,NaN,SUBARU,OUTBACK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1676297,1786956,778095d76b78da268140342a5b710810cab741cfd0febb...,03/24/2024 12:00:00 PM,2,DRIVER,NaN,1701765.0,NaN,HONDA,CR-V,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1676298,1788463,0759126cbdafc3bdd87d00cdecaf401dd79489914d4a41...,03/24/2024 02:25:00 PM,1,DRIVER,NaN,1703231.0,NaN,HONDA,ACCORD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1676299,1788464,0759126cbdafc3bdd87d00cdecaf401dd79489914d4a41...,03/24/2024 02:25:00 PM,2,DRIVER,NaN,1703256.0,NaN,CHEVROLET,SILVERADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1676300,1789016,ef51edc78bb4718c7286526f9968f6980cfea6ffb62454...,03/24/2024 10:30:00 PM,1,DRIVER,NaN,1703758.0,NaN,HYUNDAI,OTHER (EXPLAIN IN NARRATIVE),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1676301,1789019,ef51edc78bb4718c7286526f9968f6980cfea6ffb62454...,03/24/2024 10:30:00 PM,2,PARKED,NaN,1703765.0,NaN,GENERAL MOTORS CORPORATION (GMC),TERRAIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
#1803633 rows × 29 columns
len(pd.unique(dfd['CRASH_RECORD_ID']).tolist()) #819923
dfd

,PERSON_ID,PERSON_TYPE,CRASH_RECORD_ID,VEHICLE_ID,CRASH_DATE,SEAT_NO,CITY,STATE,ZIPCODE,SEX,...,EMS_RUN_NO,DRIVER_ACTION,DRIVER_VISION,PHYSICAL_CONDITION,PEDPEDAL_ACTION,PEDPEDAL_VISIBILITY,PEDPEDAL_LOCATION,BAC_RESULT,BAC_RESULT VALUE,CELL_PHONE_USE
0,O749947,DRIVER,81dc0de2ed92aa62baccab641fa377be7feb1cc47e6554...,834816.0,09/28/2019 03:30:00 AM,NaN,CHICAGO,IL,60651,M,...,NaN,UNKNOWN,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
1,O871921,DRIVER,af84fb5c8d996fcd3aefd36593c3a02e6e7509eeb27568...,827212.0,04/13/2020 10:50:00 PM,NaN,CHICAGO,IL,60620,M,...,NaN,NONE,NOT OBSCURED,NORMAL,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
2,O10018,DRIVER,71162af7bf22799b776547132ebf134b5b438dcf3dac6b...,9579.0,11/01/2015 05:00:00 AM,NaN,NaN,NaN,NaN,X,...,NaN,IMPROPER BACKING,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
3,O10038,DRIVER,c21c476e2ccc41af550b5d858d22aaac4ffc88745a1700...,9598.0,11/01/2015 08:00:00 AM,NaN,NaN,NaN,NaN,X,...,NaN,UNKNOWN,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
4,O10039,DRIVER,eb390a4c8e114c69488f5fb8a097fe629f5a92fd528cf4...,9600.0,11/01/2015 10:15:00 AM,NaN,NaN,NaN,NaN,X,...,NaN,UNKNOWN,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1803628,P382511,PASSENGER,9d3f0c15dd51b93fffae416782b4e9897c3227a9478848...,1646504.0,12/23/2023 08:25:00 PM,4.0,NaN,NaN,NaN,F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1803629,P382512,PASSENGER,9d3f0c15dd51b93fffae416782b4e9897c3227a9478848...,1646507.0,12/23/2023 08:25:00 PM,3.0,CHICAGO,IL,60644,F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1803630,P382517,PASSENGER,ec0e505e7c3b010648e71656c1c936ccfddeaef8fc176c...,1646540.0,12/23/2023 04:55:00 PM,3.0,NaN,NaN,NaN,F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1803631,P382518,PASSENGER,ec0e505e7c3b010648e71656c1c936ccfddeaef8fc176c...,1646540.0,12/23/2023 04:55:00 PM,4.0,NaN,NaN,NaN,F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1803632,P382519,PASSENGER,ec0e505e7c3b010648e71656c1c936ccfddeaef8fc176c...,1646540.0,12/23/2023 04:55:00 PM,6.0,NaN,NaN,NaN,F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
all_old_ids = set(pd.unique(dfv['CRASH_RECORD_ID']).tolist() + pd.unique(dfd['CRASH_RECORD_ID']).tolist())
new_id_mapping = {old_id: new_id for new_id, old_id in enumerate(all_old_ids)}

dfd['new_id'] = dfd['CRASH_RECORD_ID'].map(new_id_mapping)
dfv['new_id'] = dfv['CRASH_RECORD_ID'].map(new_id_mapping)

In [20]:
dfd = dfd.drop(columns=['CRASH_RECORD_ID'])
dfv = dfv.drop(columns=['CRASH_RECORD_ID'])

In [21]:
dfd.rename(columns={'new_id': 'CRASH_RECORD_ID'}, inplace=True)
dfv.rename(columns={'new_id': 'CRASH_RECORD_ID'}, inplace=True)

In [22]:
dfv

,CRASH_UNIT_ID,CRASH_DATE,UNIT_NO,UNIT_TYPE,NUM_PASSENGERS,VEHICLE_ID,CMRC_VEH_I,MAKE,MODEL,LIC_PLATE_STATE,...,TRAILER2_LENGTH,TOTAL_VEHICLE_LENGTH,AXLE_CNT,VEHICLE_CONFIG,CARGO_BODY_TYPE,LOAD_TYPE,HAZMAT_OUT_OF_SERVICE_I,MCS_OUT_OF_SERVICE_I,HAZMAT_CLASS,CRASH_RECORD_ID
0,1717556,12/06/2023 03:24:00 PM,1,DRIVER,NaN,1634931.0,NaN,NISSAN,SENTRA,IL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,212397
1,1717574,12/06/2023 04:00:00 PM,2,DRIVER,NaN,1634978.0,NaN,CHRYSLER,SEBRING,IL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10090
2,1717579,12/06/2023 04:30:00 PM,1,DRIVER,NaN,1634948.0,NaN,SUBARU,OUTBACK,IL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43673
3,1720118,12/10/2023 12:12:00 PM,1,DRIVER,NaN,1637401.0,NaN,TOYOTA,RAV4,IL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,396614
4,1720119,12/10/2023 12:12:00 PM,2,DRIVER,NaN,1637408.0,NaN,SUBARU,OUTBACK,OK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,396614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1676297,1786956,03/24/2024 12:00:00 PM,2,DRIVER,NaN,1701765.0,NaN,HONDA,CR-V,IL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141352
1676298,1788463,03/24/2024 02:25:00 PM,1,DRIVER,NaN,1703231.0,NaN,HONDA,ACCORD,IL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,431327
1676299,1788464,03/24/2024 02:25:00 PM,2,DRIVER,NaN,1703256.0,NaN,CHEVROLET,SILVERADO,IL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,431327
1676300,1789016,03/24/2024 10:30:00 PM,1,DRIVER,NaN,1703758.0,NaN,HYUNDAI,OTHER (EXPLAIN IN NARRATIVE),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,447415
1676301,1789019,03/24/2024 10:30:00 PM,2,PARKED,NaN,1703765.0,NaN,GENERAL MOTORS CORPORATION (GMC),TERRAIN,IL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,447415

In [23]:
dfd.to_csv('Traffic_Crashes_People_20240409_reduced.csv')

In [24]:
dfv.to_csv('Traffic_Crashes_Vehicles_20240409_reduced.csv')

In [17]:
dfd['CRASH_RECORD_ID']

0          81dc0de2ed92aa62baccab641fa377be7feb1cc47e6554...
1          af84fb5c8d996fcd3aefd36593c3a02e6e7509eeb27568...
2          71162af7bf22799b776547132ebf134b5b438dcf3dac6b...
3          c21c476e2ccc41af550b5d858d22aaac4ffc88745a1700...
4          eb390a4c8e114c69488f5fb8a097fe629f5a92fd528cf4...
                                 ...
1803628    9d3f0c15dd51b93fffae416782b4e9897c3227a9478848...
1803629    9d3f0c15dd51b93fffae416782b4e9897c3227a9478848...
1803630    ec0e505e7c3b010648e71656c1c936ccfddeaef8fc176c...
1803631    ec0e505e7c3b010648e71656c1c936ccfddeaef8fc176c...
1803632    ec0e505e7c3b010648e71656c1c936ccfddeaef8fc176c...
Name: CRASH_RECORD_ID, Length: 1803633, dtype: object

In [ ]:
min_new_id = min(dfd['new_id'].min(), dfv['new_id'].min())
max_new_id = max(dfd['new_id'].max(), dfv['new_id'].max())
print("\nRange of new IDs:", min_new_id, "to", max_new_id)